@firewall_updater_HostAddress = http://localhost:5298

GET {{firewall_updater_HostAddress}}/todos/
Accept: application/json

###

GET {{firewall_updater_HostAddress}}/todos/1
Accept: application/json

###
